<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:fase2="http://rep.oio.dk/skat.dk/eindkomst/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" name="IndkomstOplysningPersonHentService" targetNamespace="http://rep.oio.dk/skat.dk/eindkomst/">
         <xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:documentation>ABONNEMENT 
Servicen udstiller indkomstoplysninger for en eller flere fysiske eller juridiske personer. (Fysiske personer er personer identificeret med dansk CPR-nummer. Juridiske personer er virksomheder identificeret med CVR- eller SE-nummer) 

Servicen stiller indkomstoplysninger til rådighed for myndigheder og andre, som iht. eIndkomstlovens § 7 stk. 1, jf. § 15 stk. 1 i eIndkomstbekendtgørelsen, kan anvende oplysninger fra indkomstregistret. 

Anvendelsen af servicen er betinget af, at de pågældende har indgået en abonnementsaftale med told- og skatteforvaltningen herom, jf. § 7 stk. 4 i lov om et indkomstregister. 

Servicen udstilles ikke til enhver og må således alene anvendes af kendte brugere, dvs. af de myndighe-der m.fl., som abonnerer på indkomstoplysninger. 

Servicen kan give adgang til alle indkomstoplysninger eller en begrænset mængde af indkomstoplysninger afhængig af abonnent. De oplysninger, som en abonnent ikke har adgang til, filtreres fra (fjernes før udstil-ling til abonnenten) på grundlag af oplysning om abonnent, abonnement og anvendelsesformål. 
Servicen kan anvendes til præsentation af oplysninger via en brugergrænseflade for en sagsbehandler. 

Begrænsning i kredsen af indkomstmodtagere, som der stilles oplysninger til rådighed for, sker hos den enkelte abonnent og fastlægges individuelt med abonnenten i den aftale, der skal indgås iht. lov og be-kendtgørelse. Eksempelvis begrænser servicen ikke adgangen for en kommune til alene at omfatte de borgere, som bor i kommunen. Denne begrænsning skal ske hos kommunen. 
Indkomstoplysninger kan stilles til rådighed for en specifik indkomstudbetaler, eksempelvis arbejdsgiver. 

Indkomstoplysninger stilles til rådighed ubearbejdet. Eventuel tolkning, sammenstilling, summering o. lign. af indkomstoplysninger sker hos den, som har adgang til indkomstoplysninger på grundlag af den lovgiv-ning, som gælder for området. Indkomstoplysninger, som er tilbageført stilles også til rådighed. 

UDFYLDELSE AF SØGEKRITERIER 
For at hente oplysninger skal der udfyldes søgeperiode for enten lønperiode eller basismåned. 
Enten skal SøgeDatoFra og SøgeDatoTil (lønperiode) eller også skal SøgeÅrMånedFra og SøgeÅrMånedTil (basismåned) udfyldes. 

SØGNING MED BASISMÅNED 
En basismåned er den måned, som indkomstoplysningerne, rent skattemæssigt hører til i. 
Hvis SøgeÅrMånedFra er udfyldt, hentes der oplysninger fra og med det angivne år og måned. Hvis både SøgeÅrMånedFra og SøgeÅrMånedTil er udfyldt hentes, der oplysninger for den angivne periode. Angives basismånedsperioden til eksempelvis 201001 ? 201004, så hentes alle indkomstoplysninger, der har basismåned i denne periode. 

SØGNING MED LØNPERIODE 
Lønperioden er den periode, som indkomstmodtageren kender fra sin lønseddel, eksempelvis løn for peri-oden 20. december 2009 til 19. januar 2010. 
Der hentes der oplysninger, hvor lønperiode er helt eller delvis omfattet af den angivne søgeperiode. 

LOGNING 
En myndigheds (abonnents) anmodning om adgang til oplysninger kan udstilles til den, som oplysningerne vedrører, eksempelvis via Skattemappen for personer. Om der sker udstilling fastlægges i abonnements-aftalen for hver abonnent for hvert adgangsformål. Eventuel oplysning fra en abonnent om medarbejder-identifikation udstilles dog ikke. 
Der stilles ikke oplysninger til rådighed, hvis der er krav om logning, og adgangen til oplysningerne ikke kan logges. 

ANDRE FORHOLD 
Hvis det viser sig, at der hentes for stor en mængde af indkomstoplysninger på en gang, så afvises ser-vices kald. Serviceanvender må så enten begrænse sine søge kriterier eller anvende en asynkron service til hentning af oplysninger. Begrænsning i søgekriterier kan bestå i reduktion af antallet af CPR-numre, som der søges på, eller reduktion af søgeperioden. 
Servicen kan tillige efter aftale mellem abonnent og told- og skatteforvaltningen anvendes i digitale selvbe-tjeningsløsninger til borgere.</xs:documentation>
            <xs:documentation>r25283</xs:documentation>
         </xs:annotation>
         <wsdl:types>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://rep.oio.dk/skat.dk/eindkomst/">
               <xsd:include schemaLocation="skat_dk/eindkomst/IndkomstOplysningPersonHentInterface.xsd"/>
            </xsd:schema>
         </wsdl:types>
         <wsdl:message name="IndkomstOplysningPersonHentServiceRequest">
            <wsdl:part element="fase2:IndkomstOplysningPersonHent_I" name="Request"/>
         </wsdl:message>
         <wsdl:message name="IndkomstOplysningPersonHentServiceResponse">
            <wsdl:part element="fase2:IndkomstOplysningPersonHent_O" name="Response"/>
         </wsdl:message>
         <wsdl:portType name="IndkomstOplysningPersonHentServicePortType">
            <wsdl:operation name="getIndkomstOplysningPersonHent">
               <wsdl:input message="fase2:IndkomstOplysningPersonHentServiceRequest"/>
               <wsdl:output message="fase2:IndkomstOplysningPersonHentServiceResponse"/>
            </wsdl:operation>
         </wsdl:portType>
         
<wsdl:binding name="IndkomstOplysningPersonHentServiceBinding" type="fase2:IndkomstOplysningPersonHentServicePortType">
		<wsp:PolicyReference URI="#wss10_anonymous_with_cert_policy"/>
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getIndkomstOplysningPersonHent">
			<soap:operation soapAction="getIndkomstOplysningPersonHent"/>
			<wsdl:input>
				<soap:body parts="Request" use="literal"/>
				<wsp:PolicyReference URI="#WSS10Anonymous_with_Certificates_input_policy"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="Response" use="literal"/>
				<wsp:PolicyReference URI="#WSS10anonymous_with_certs_output_policy"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IndkomstOplysningPersonHentServiceBindingQSService">
		<wsdl:port name="IndkomstOplysningPersonHentServiceBindingQSPort" binding="fase2:IndkomstOplysningPersonHentServiceBinding">
			<soap:address location="https://services.extranet.demo.skat.dk/vericert/services/IndkomstOplysningPersonHentV2ServicePort"/>
		</wsdl:port>
	</wsdl:service>

	<wsp:Policy wsu:Id="wss10_anonymous_with_cert_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:AsymmetricBinding>
					<wsp:Policy>
						<sp:InitiatorToken>
							<wsp:Policy>
								<sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:InitiatorToken>
						<sp:RecipientToken>
							<wsp:Policy>
								<sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:RecipientToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Strict />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
						<sp:ProtectTokens />
						<sp:OnlySignEntireHeadersAndBody />
						<sp:SupportingTokens>
							<wsp:Policy>
								<sp:UsernameToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:NoPassword />
										<sp:WssUsernameToken10 />
									</wsp:Policy>
								</sp:UsernameToken>
							</wsp:Policy>
						</sp:SupportingTokens>
					</wsp:Policy>
				</sp:AsymmetricBinding>
				<sp:Wss10>
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
					</wsp:Policy>
				</sp:Wss10>
			</wsp:All>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
									<wsp:Policy>
										<sp:HttpBasicAuthentication />
									</wsp:Policy>
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:SupportingTokens>
							<wsp:Policy>
								<sp:UsernameToken sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/Never">
									<wsp:Policy>
										<sp:NoPassword />
										<sp:WssUsernameToken10 />
									</wsp:Policy>
								</sp:UsernameToken>
							</wsp:Policy>
						</sp:SupportingTokens>
					</wsp:Policy>
				</sp:TransportBinding>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="WSS10Anonymous_with_Certificates_input_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts>
					<sp:Body />
				</sp:SignedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsp:Policy wsu:Id="WSS10anonymous_with_certs_output_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:SignedParts>
					<sp:Header />
				</sp:SignedParts>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>

</wsdl:definitions>
