//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.42000
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dk.skat.eksternwiki.demotin
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/", ConfigurationName="dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHentServicePortType", ProtectionLevel = System.Net.Security.ProtectionLevel.Sign)]
    public interface IndkomstOplysningPersonHentServicePortType
    {
        
        // CODEGEN: Der oprettes en meddelelseskontrakt, da handlingen getIndkomstOplysningPersonHent hverken er en RPC- eller dokumentwrapper.
        [System.ServiceModel.OperationContractAttribute(Action="getIndkomstOplysningPersonHent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentResponse getIndkomstOplysningPersonHent(dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_IType
    {
        
        private HovedOplysningerType hovedOplysningerField;
        
        private IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddata indkomstOplysningPersonInddataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/", Order=0)]
        public HovedOplysningerType HovedOplysninger
        {
            get
            {
                return this.hovedOplysningerField;
            }
            set
            {
                this.hovedOplysningerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddata IndkomstOplysningPersonInddata
        {
            get
            {
                return this.indkomstOplysningPersonInddataField;
            }
            set
            {
                this.indkomstOplysningPersonInddataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class HovedOplysningerType
    {
        
        private string transaktionIdentifikatorField;
        
        private System.DateTime transaktionTidField;
        
        private bool transaktionTidFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransaktionIdentifikator
        {
            get
            {
                return this.transaktionIdentifikatorField;
            }
            set
            {
                this.transaktionIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TransaktionTid
        {
            get
            {
                return this.transaktionTidField;
            }
            set
            {
                this.transaktionTidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaktionTidSpecified
        {
            get
            {
                return this.transaktionTidFieldSpecified;
            }
            set
            {
                this.transaktionTidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class VirksomhedLoenPeriodeStrukturType
    {
        
        private string angivelseVirksomhedEgenIdentifikatorField;
        
        private AngivelsePeriodeStrukturType angivelsePeriodeStrukturField;
        
        private string ansaettelseforholdMedarbejderIdentifikatorField;
        
        private System.DateTime indkomstPersonGruppeDispositionDatoField;
        
        private bool indkomstPersonGruppeDispositionDatoFieldSpecified;
        
        private AngivelseBlanketIndholdStrukturType angivelseBlanketIndholdStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelse/xml/schemas/20071202/", Order=0)]
        public string AngivelseVirksomhedEgenIdentifikator
        {
            get
            {
                return this.angivelseVirksomhedEgenIdentifikatorField;
            }
            set
            {
                this.angivelseVirksomhedEgenIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AngivelsePeriodeStrukturType AngivelsePeriodeStruktur
        {
            get
            {
                return this.angivelsePeriodeStrukturField;
            }
            set
            {
                this.angivelsePeriodeStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/ansaettelseforhold/xml/schemas/20071202" +
            "/", Order=2)]
        public string AnsaettelseforholdMedarbejderIdentifikator
        {
            get
            {
                return this.ansaettelseforholdMedarbejderIdentifikatorField;
            }
            set
            {
                this.ansaettelseforholdMedarbejderIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstpersongruppe/xml/schemas/200712" +
            "02/", DataType="date", Order=3)]
        public System.DateTime IndkomstPersonGruppeDispositionDato
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoField;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndkomstPersonGruppeDispositionDatoSpecified
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoFieldSpecified;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AngivelseBlanketIndholdStrukturType AngivelseBlanketIndholdStruktur
        {
            get
            {
                return this.angivelseBlanketIndholdStrukturField;
            }
            set
            {
                this.angivelseBlanketIndholdStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelsePeriodeStrukturType
    {
        
        private DateIntervalType angivelsePeriodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelse/xml/schemas/20071202/", Order=0)]
        public DateIntervalType AngivelsePeriode
        {
            get
            {
                return this.angivelsePeriodeField;
            }
            set
            {
                this.angivelsePeriodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/09/01/")]
    public partial class DateIntervalType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StartDate", typeof(System.DateTime), Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/09/01/", DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("EndDate", typeof(System.DateTime), Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/04/15/", DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DurationMeasure", typeof(string), DataType="duration", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/09/01/", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/xkom.dk/xml/schemas/2006/09/01/:StartDate")]
        StartDate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://rep.oio.dk/xkom.dk/xml/schemas/2007/04/15/:EndDate")]
        EndDate,
        
        /// <remarks/>
        DurationMeasure,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseBlanketIndholdStrukturType
    {
        
        private AngivelseNiveau1Type[] angivelseOplysningSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau1", IsNullable=false)]
        public AngivelseNiveau1Type[] AngivelseOplysningSamling
        {
            get
            {
                return this.angivelseOplysningSamlingField;
            }
            set
            {
                this.angivelseOplysningSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau1Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        private AngivelseNiveau2Type[] underAngivelseSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau2", IsNullable=false)]
        public AngivelseNiveau2Type[] UnderAngivelseSamling
        {
            get
            {
                return this.underAngivelseSamlingField;
            }
            set
            {
                this.underAngivelseSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseFeltIndholdStrukturType
    {
        
        private BlanketFeltEnhedStrukturType blanketFeltEnhedStrukturField;
        
        private string angivelseFeltIndholdTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BlanketFeltEnhedStrukturType BlanketFeltEnhedStruktur
        {
            get
            {
                return this.blanketFeltEnhedStrukturField;
            }
            set
            {
                this.blanketFeltEnhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelsefelt/xml/schemas/20071202/", Order=1)]
        public string AngivelseFeltIndholdTekst
        {
            get
            {
                return this.angivelseFeltIndholdTekstField;
            }
            set
            {
                this.angivelseFeltIndholdTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class BlanketFeltEnhedStrukturType
    {
        
        private string blanketFeltNummerIdentifikatorField;
        
        private string feltEnhedTypeKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanketfelt/xml/schemas/20071202/", DataType="integer", Order=0)]
        public string BlanketFeltNummerIdentifikator
        {
            get
            {
                return this.blanketFeltNummerIdentifikatorField;
            }
            set
            {
                this.blanketFeltNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/feltenhedtype/xml/schemas/20071202/", DataType="integer", Order=1)]
        public string FeltEnhedTypeKode
        {
            get
            {
                return this.feltEnhedTypeKodeField;
            }
            set
            {
                this.feltEnhedTypeKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau2Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        private AngivelseNiveau3Type[] underAngivelseSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau3", IsNullable=false)]
        public AngivelseNiveau3Type[] UnderAngivelseSamling
        {
            get
            {
                return this.underAngivelseSamlingField;
            }
            set
            {
                this.underAngivelseSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau3Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        private AngivelseNiveau4Type[] underAngivelseSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseNiveau4", IsNullable=false)]
        public AngivelseNiveau4Type[] UnderAngivelseSamling
        {
            get
            {
                return this.underAngivelseSamlingField;
            }
            set
            {
                this.underAngivelseSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AngivelseNiveau4Type
    {
        
        private string blanketNummerIdentifikatorField;
        
        private AngivelseFeltIndholdStrukturType[] angivelseFeltSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/blanket/xml/schemas/20071202/", Order=0)]
        public string BlanketNummerIdentifikator
        {
            get
            {
                return this.blanketNummerIdentifikatorField;
            }
            set
            {
                this.blanketNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AngivelseFeltIndholdStruktur", IsNullable=false)]
        public AngivelseFeltIndholdStrukturType[] AngivelseFeltSamling
        {
            get
            {
                return this.angivelseFeltSamlingField;
            }
            set
            {
                this.angivelseFeltSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningVirksomhedStrukturType
    {
        
        private IndberetningForVirksomhedStrukturType indberetningForVirksomhedStrukturField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndkomstOplysningVirksomhedStrukturTypeIndberetningPligtigVirksomhed[] indkomstOplysningVirksomhedSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningForVirksomhedStrukturType IndberetningForVirksomhedStruktur
        {
            get
            {
                return this.indberetningForVirksomhedStrukturField;
            }
            set
            {
                this.indberetningForVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IndberetningPligtigVirksomhed", IsNullable=false)]
        public IndkomstOplysningVirksomhedStrukturTypeIndberetningPligtigVirksomhed[] IndkomstOplysningVirksomhedSamling
        {
            get
            {
                return this.indkomstOplysningVirksomhedSamlingField;
            }
            set
            {
                this.indkomstOplysningVirksomhedSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningForVirksomhedStrukturType
    {
        
        private IndberetningForVirksomhedStrukturTypeIndberetningForVirksomhed indberetningForVirksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningForVirksomhedStrukturTypeIndberetningForVirksomhed IndberetningForVirksomhed
        {
            get
            {
                return this.indberetningForVirksomhedField;
            }
            set
            {
                this.indberetningForVirksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningForVirksomhedStrukturTypeIndberetningForVirksomhed
    {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator
        {
            get
            {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set
            {
                this.virksomhedSENummerIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningVirksomhedStrukturTypeIndberetningPligtigVirksomhed
    {
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private VirksomhedLoenPeriodeStrukturType[] indkomstLoenPeriodeSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VirksomhedLoenPeriodeStruktur", IsNullable=false)]
        public VirksomhedLoenPeriodeStrukturType[] IndkomstLoenPeriodeSamling
        {
            get
            {
                return this.indkomstLoenPeriodeSamlingField;
            }
            set
            {
                this.indkomstLoenPeriodeSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningPligtigVirksomhedStrukturType
    {
        
        private IndberetningPligtigVirksomhedStrukturTypeIndberetningPligtigVirksomhed indberetningPligtigVirksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningPligtigVirksomhedStrukturTypeIndberetningPligtigVirksomhed IndberetningPligtigVirksomhed
        {
            get
            {
                return this.indberetningPligtigVirksomhedField;
            }
            set
            {
                this.indberetningPligtigVirksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndberetningPligtigVirksomhedStrukturTypeIndberetningPligtigVirksomhed
    {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator
        {
            get
            {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set
            {
                this.virksomhedSENummerIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType
    {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme
        {
            get
            {
                return this.schemeField;
            }
            set
            {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AlternativAdresseStrukturType
    {
        
        private string alternativAdresseAdresseLinie1Field;
        
        private string alternativAdresseAdresseLinie2Field;
        
        private string alternativAdresseAdresseLinie3Field;
        
        private string alternativAdresseAdresseLinie4Field;
        
        private string alternativAdresseAdresseLinie5Field;
        
        private CountryIdentificationCodeType landKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=0)]
        public string AlternativAdresseAdresseLinie1
        {
            get
            {
                return this.alternativAdresseAdresseLinie1Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=1)]
        public string AlternativAdresseAdresseLinie2
        {
            get
            {
                return this.alternativAdresseAdresseLinie2Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=2)]
        public string AlternativAdresseAdresseLinie3
        {
            get
            {
                return this.alternativAdresseAdresseLinie3Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=3)]
        public string AlternativAdresseAdresseLinie4
        {
            get
            {
                return this.alternativAdresseAdresseLinie4Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/alternativadresse/xml/schemas/20071202/" +
            "", Order=4)]
        public string AlternativAdresseAdresseLinie5
        {
            get
            {
                return this.alternativAdresseAdresseLinie5Field;
            }
            set
            {
                this.alternativAdresseAdresseLinie5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/land/xml/schemas/20071202/", Order=5)]
        public CountryIdentificationCodeType LandKode
        {
            get
            {
                return this.landKodeField;
            }
            set
            {
                this.landKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class SupplerendePersonOplysningStrukturType
    {
        
        private string tINIdentifikatorField;
        
        private string personNameField;
        
        private string supplerendePersonOplysningFoedselTekstField;
        
        private PersonGenderCodeType personGenderCodeField;
        
        private bool personGenderCodeFieldSpecified;
        
        private AlternativAdresseStrukturType alternativAdresseStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://eksternwiki.skat.dk/oioxml/skat_dk/eIndkomst/person/", Order=0)]
        public string TINIdentifikator
        {
            get
            {
                return this.tINIdentifikatorField;
            }
            set
            {
                this.tINIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/", Order=1)]
        public string PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/supplerendepersonoplysning/xml/schemas/" +
            "20071202/", Order=2)]
        public string SupplerendePersonOplysningFoedselTekst
        {
            get
            {
                return this.supplerendePersonOplysningFoedselTekstField;
            }
            set
            {
                this.supplerendePersonOplysningFoedselTekstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/", Order=3)]
        public PersonGenderCodeType PersonGenderCode
        {
            get
            {
                return this.personGenderCodeField;
            }
            set
            {
                this.personGenderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonGenderCodeSpecified
        {
            get
            {
                return this.personGenderCodeFieldSpecified;
            }
            set
            {
                this.personGenderCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public AlternativAdresseStrukturType AlternativAdresseStruktur
        {
            get
            {
                return this.alternativAdresseStrukturField;
            }
            set
            {
                this.alternativAdresseStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")]
    public enum PersonGenderCodeType
    {
        
        /// <remarks/>
        male,
        
        /// <remarks/>
        female,
        
        /// <remarks/>
        unspecified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class LoenPeriodeOplysningStrukturType
    {
        
        private string angivelseVirksomhedEgenIdentifikatorField;
        
        private AngivelsePeriodeStrukturType angivelsePeriodeStrukturField;
        
        private string ansaettelseforholdMedarbejderIdentifikatorField;
        
        private System.DateTime indkomstPersonGruppeDispositionDatoField;
        
        private bool indkomstPersonGruppeDispositionDatoFieldSpecified;
        
        private SupplerendePersonOplysningStrukturType supplerendePersonOplysningStrukturField;
        
        private AngivelseBlanketIndholdStrukturType angivelseBlanketIndholdStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/angivelse/xml/schemas/20071202/", Order=0)]
        public string AngivelseVirksomhedEgenIdentifikator
        {
            get
            {
                return this.angivelseVirksomhedEgenIdentifikatorField;
            }
            set
            {
                this.angivelseVirksomhedEgenIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AngivelsePeriodeStrukturType AngivelsePeriodeStruktur
        {
            get
            {
                return this.angivelsePeriodeStrukturField;
            }
            set
            {
                this.angivelsePeriodeStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/ansaettelseforhold/xml/schemas/20071202" +
            "/", Order=2)]
        public string AnsaettelseforholdMedarbejderIdentifikator
        {
            get
            {
                return this.ansaettelseforholdMedarbejderIdentifikatorField;
            }
            set
            {
                this.ansaettelseforholdMedarbejderIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstpersongruppe/xml/schemas/200712" +
            "02/", DataType="date", Order=3)]
        public System.DateTime IndkomstPersonGruppeDispositionDato
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoField;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndkomstPersonGruppeDispositionDatoSpecified
        {
            get
            {
                return this.indkomstPersonGruppeDispositionDatoFieldSpecified;
            }
            set
            {
                this.indkomstPersonGruppeDispositionDatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SupplerendePersonOplysningStrukturType SupplerendePersonOplysningStruktur
        {
            get
            {
                return this.supplerendePersonOplysningStrukturField;
            }
            set
            {
                this.supplerendePersonOplysningStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AngivelseBlanketIndholdStrukturType AngivelseBlanketIndholdStruktur
        {
            get
            {
                return this.angivelseBlanketIndholdStrukturField;
            }
            set
            {
                this.angivelseBlanketIndholdStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonStrukturType
    {
        
        private string personCivilRegistrationIdentifierField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndkomstOplysningPersonStrukturTypeIndberetningPligtigVirksomhed[] indkomstOplysningSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string PersonCivilRegistrationIdentifier
        {
            get
            {
                return this.personCivilRegistrationIdentifierField;
            }
            set
            {
                this.personCivilRegistrationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("IndberetningPligtigVirksomhed", IsNullable=false)]
        public IndkomstOplysningPersonStrukturTypeIndberetningPligtigVirksomhed[] IndkomstOplysningSamling
        {
            get
            {
                return this.indkomstOplysningSamlingField;
            }
            set
            {
                this.indkomstOplysningSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonStrukturTypeIndberetningPligtigVirksomhed
    {
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private LoenPeriodeOplysningStrukturType[] indkomstLoenPeriodeSamlingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LoenPeriodeOplysningStruktur", IsNullable=false)]
        public LoenPeriodeOplysningStrukturType[] IndkomstLoenPeriodeSamling
        {
            get
            {
                return this.indkomstLoenPeriodeSamlingField;
            }
            set
            {
                this.indkomstLoenPeriodeSamlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class FejlStrukturType
    {
        
        private string fejlIdentifikatorField;
        
        private string fejlTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string FejlIdentifikator
        {
            get
            {
                return this.fejlIdentifikatorField;
            }
            set
            {
                this.fejlIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FejlTekst
        {
            get
            {
                return this.fejlTekstField;
            }
            set
            {
                this.fejlTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class AdvisStrukturType
    {
        
        private string advisIdentifikatorField;
        
        private string advisTekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string AdvisIdentifikator
        {
            get
            {
                return this.advisIdentifikatorField;
            }
            set
            {
                this.advisIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AdvisTekst
        {
            get
            {
                return this.advisTekstField;
            }
            set
            {
                this.advisTekstField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/")]
    public partial class HovedOplysningerSvarType
    {
        
        private string transaktionIdentifikatorField;
        
        private string serviceIdentifikatorField;
        
        private System.DateTime transaktionTidField;
        
        private bool transaktionTidFieldSpecified;
        
        private object[] svarStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransaktionIdentifikator
        {
            get
            {
                return this.transaktionIdentifikatorField;
            }
            set
            {
                this.transaktionIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceIdentifikator
        {
            get
            {
                return this.serviceIdentifikatorField;
            }
            set
            {
                this.serviceIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TransaktionTid
        {
            get
            {
                return this.transaktionTidField;
            }
            set
            {
                this.transaktionTidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransaktionTidSpecified
        {
            get
            {
                return this.transaktionTidFieldSpecified;
            }
            set
            {
                this.transaktionTidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdvisStruktur", typeof(AdvisStrukturType), IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("FejlStruktur", typeof(FejlStrukturType), IsNullable=false)]
        public object[] SvarStruktur
        {
            get
            {
                return this.svarStrukturField;
            }
            set
            {
                this.svarStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_OType
    {
        
        private HovedOplysningerSvarType hovedOplysningerSvarField;
        
        private IndkomstOplysningPersonHent_OTypeIndkomstPersonUddata indkomstPersonUddataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/basis/kontekst/xml/schemas/2006/09/01/", Order=0)]
        public HovedOplysningerSvarType HovedOplysningerSvar
        {
            get
            {
                return this.hovedOplysningerSvarField;
            }
            set
            {
                this.hovedOplysningerSvarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IndkomstOplysningPersonHent_OTypeIndkomstPersonUddata IndkomstPersonUddata
        {
            get
            {
                return this.indkomstPersonUddataField;
            }
            set
            {
                this.indkomstPersonUddataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_OTypeIndkomstPersonUddata
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningPersonSamling", typeof(IndkomstOplysningPersonHent_OTypeIndkomstPersonUddataIndkomstOplysningPersonSamling), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningVirksomhedSamling", typeof(IndkomstOplysningPersonHent_OTypeIndkomstPersonUddataIndkomstOplysningVirksomhedSamling), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_OTypeIndkomstPersonUddataIndkomstOplysningPersonSamling
    {
        
        private IndkomstOplysningPersonStrukturType[] indkomstOplysningPersonStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningPersonStruktur", Order=0)]
        public IndkomstOplysningPersonStrukturType[] IndkomstOplysningPersonStruktur
        {
            get
            {
                return this.indkomstOplysningPersonStrukturField;
            }
            set
            {
                this.indkomstOplysningPersonStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_OTypeIndkomstPersonUddataIndkomstOplysningVirksomhedSamling
    {
        
        private IndkomstOplysningVirksomhedStrukturType[] indkomstOplysningVirksomhedStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstOplysningVirksomhedStruktur", Order=0)]
        public IndkomstOplysningVirksomhedStrukturType[] IndkomstOplysningVirksomhedStruktur
        {
            get
            {
                return this.indkomstOplysningVirksomhedStrukturField;
            }
            set
            {
                this.indkomstOplysningVirksomhedStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class VirksomhedIndkomstSoegeStrukturType
    {
        
        private IndberetningForVirksomhedStrukturType indberetningForVirksomhedStrukturField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private SoegePeriodeLukketStrukturType soegePeriodeLukketStrukturField;
        
        private SoegeAarMaanedLukketStrukturType soegeAarMaanedLukketStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IndberetningForVirksomhedStrukturType IndberetningForVirksomhedStruktur
        {
            get
            {
                return this.indberetningForVirksomhedStrukturField;
            }
            set
            {
                this.indberetningForVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegePeriodeLukketStrukturType SoegePeriodeLukketStruktur
        {
            get
            {
                return this.soegePeriodeLukketStrukturField;
            }
            set
            {
                this.soegePeriodeLukketStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SoegeAarMaanedLukketStrukturType SoegeAarMaanedLukketStruktur
        {
            get
            {
                return this.soegeAarMaanedLukketStrukturField;
            }
            set
            {
                this.soegeAarMaanedLukketStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class SoegePeriodeLukketStrukturType
    {
        
        private DateIntervalType dateIntervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2007/09/01/", Order=0)]
        public DateIntervalType DateInterval
        {
            get
            {
                return this.dateIntervalField;
            }
            set
            {
                this.dateIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class SoegeAarMaanedLukketStrukturType
    {
        
        private string soegeAarMaanedFraKodeField;
        
        private string soegeAarMaanedTilKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/soegeaarmaanedfrakode/xml/schemas/20071" +
            "202/", DataType="integer", Order=0)]
        public string SoegeAarMaanedFraKode
        {
            get
            {
                return this.soegeAarMaanedFraKodeField;
            }
            set
            {
                this.soegeAarMaanedFraKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/soegeaarmaanedtilkode/xml/schemas/20071" +
            "202/", DataType="integer", Order=1)]
        public string SoegeAarMaanedTilKode
        {
            get
            {
                return this.soegeAarMaanedTilKodeField;
            }
            set
            {
                this.soegeAarMaanedTilKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class PersonIndkomstSoegeStrukturType
    {
        
        private string personCivilRegistrationIdentifierField;
        
        private string indkomstOplysningAdgangReferenceNummerIdentifikatorField;
        
        private IndberetningPligtigVirksomhedStrukturType indberetningPligtigVirksomhedStrukturField;
        
        private SoegePeriodeLukketStrukturType soegePeriodeLukketStrukturField;
        
        private SoegeAarMaanedLukketStrukturType soegeAarMaanedLukketStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string PersonCivilRegistrationIdentifier
        {
            get
            {
                return this.personCivilRegistrationIdentifierField;
            }
            set
            {
                this.personCivilRegistrationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangreferencenummer/" +
            "xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangReferenceNummerIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangReferenceNummerIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangReferenceNummerIdentifikatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndberetningPligtigVirksomhedStrukturType IndberetningPligtigVirksomhedStruktur
        {
            get
            {
                return this.indberetningPligtigVirksomhedStrukturField;
            }
            set
            {
                this.indberetningPligtigVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SoegePeriodeLukketStrukturType SoegePeriodeLukketStruktur
        {
            get
            {
                return this.soegePeriodeLukketStrukturField;
            }
            set
            {
                this.soegePeriodeLukketStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SoegeAarMaanedLukketStrukturType SoegeAarMaanedLukketStruktur
        {
            get
            {
                return this.soegeAarMaanedLukketStrukturField;
            }
            set
            {
                this.soegeAarMaanedLukketStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentVirksomhedStrukturType
    {
        
        private AbonnentVirksomhedStrukturTypeAbonnentVirksomhed abonnentVirksomhedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AbonnentVirksomhedStrukturTypeAbonnentVirksomhed AbonnentVirksomhed
        {
            get
            {
                return this.abonnentVirksomhedField;
            }
            set
            {
                this.abonnentVirksomhedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentVirksomhedStrukturTypeAbonnentVirksomhed
    {
        
        private string virksomhedSENummerIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/motor/class/virksomhed/xml/schemas/20080401/", Order=0)]
        public string VirksomhedSENummerIdentifikator
        {
            get
            {
                return this.virksomhedSENummerIdentifikatorField;
            }
            set
            {
                this.virksomhedSENummerIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentStrukturType
    {
        
        private AbonnentVirksomhedStrukturType abonnentVirksomhedStrukturField;
        
        private string indkomstOplysningAdgangMedarbejderIdentifikatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AbonnentVirksomhedStrukturType AbonnentVirksomhedStruktur
        {
            get
            {
                return this.abonnentVirksomhedStrukturField;
            }
            set
            {
                this.abonnentVirksomhedStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/indkomstoplysningadgangmedarbejderident" +
            "ifikator/xml/schemas/20071202/", Order=1)]
        public string IndkomstOplysningAdgangMedarbejderIdentifikator
        {
            get
            {
                return this.indkomstOplysningAdgangMedarbejderIdentifikatorField;
            }
            set
            {
                this.indkomstOplysningAdgangMedarbejderIdentifikatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class AbonnentAdgangStrukturType
    {
        
        private string abonnentTypeKodeField;
        
        private string abonnementTypeKodeField;
        
        private string adgangFormaalTypeKodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/abonnenttype/xml/schemas/20071202/", DataType="integer", Order=0)]
        public string AbonnentTypeKode
        {
            get
            {
                return this.abonnentTypeKodeField;
            }
            set
            {
                this.abonnentTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/abonnementtype/xml/schemas/20071202/", DataType="integer", Order=1)]
        public string AbonnementTypeKode
        {
            get
            {
                return this.abonnementTypeKodeField;
            }
            set
            {
                this.abonnementTypeKodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/class/adgangformaaltype/xml/schemas/20071202/" +
            "", DataType="integer", Order=2)]
        public string AdgangFormaalTypeKode
        {
            get
            {
                return this.adgangFormaalTypeKodeField;
            }
            set
            {
                this.adgangFormaalTypeKodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddata
    {
        
        private AbonnentAdgangStrukturType abonnentAdgangStrukturField;
        
        private AbonnentStrukturType abonnentStrukturField;
        
        private IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValg indkomstOplysningValgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AbonnentAdgangStrukturType AbonnentAdgangStruktur
        {
            get
            {
                return this.abonnentAdgangStrukturField;
            }
            set
            {
                this.abonnentAdgangStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AbonnentStrukturType AbonnentStruktur
        {
            get
            {
                return this.abonnentStrukturField;
            }
            set
            {
                this.abonnentStrukturField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValg IndkomstOplysningValg
        {
            get
            {
                return this.indkomstOplysningValgField;
            }
            set
            {
                this.indkomstOplysningValgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValg
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IndkomstForVirksomhedSamling", typeof(IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValgIndkomstForVirksomhedSamling), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IndkomstPersonSamling", typeof(IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValgIndkomstPersonSamling), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValgIndkomstForVirksomhedSamling
    {
        
        private VirksomhedIndkomstSoegeStrukturType[] virksomhedIndkomstSoegeStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VirksomhedIndkomstSoegeStruktur", Order=0)]
        public VirksomhedIndkomstSoegeStrukturType[] VirksomhedIndkomstSoegeStruktur
        {
            get
            {
                return this.virksomhedIndkomstSoegeStrukturField;
            }
            set
            {
                this.virksomhedIndkomstSoegeStrukturField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rep.oio.dk/skat.dk/eindkomst/")]
    public partial class IndkomstOplysningPersonHent_ITypeIndkomstOplysningPersonInddataIndkomstOplysningValgIndkomstPersonSamling
    {
        
        private PersonIndkomstSoegeStrukturType[] personIndkomstSoegeStrukturField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonIndkomstSoegeStruktur", Order=0)]
        public PersonIndkomstSoegeStrukturType[] PersonIndkomstSoegeStruktur
        {
            get
            {
                return this.personIndkomstSoegeStrukturField;
            }
            set
            {
                this.personIndkomstSoegeStrukturField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIndkomstOplysningPersonHentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/", Order=0)]
        public dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHent_IType IndkomstOplysningPersonHent_I;
        
        public getIndkomstOplysningPersonHentRequest()
        {
        }
        
        public getIndkomstOplysningPersonHentRequest(dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHent_IType IndkomstOplysningPersonHent_I)
        {
            this.IndkomstOplysningPersonHent_I = IndkomstOplysningPersonHent_I;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIndkomstOplysningPersonHentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rep.oio.dk/skat.dk/eindkomst/", Order=0)]
        public dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHent_OType IndkomstOplysningPersonHent_O;
        
        public getIndkomstOplysningPersonHentResponse()
        {
        }
        
        public getIndkomstOplysningPersonHentResponse(dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHent_OType IndkomstOplysningPersonHent_O)
        {
            this.IndkomstOplysningPersonHent_O = IndkomstOplysningPersonHent_O;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndkomstOplysningPersonHentServicePortTypeChannel : dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHentServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndkomstOplysningPersonHentServicePortTypeClient : System.ServiceModel.ClientBase<dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHentServicePortType>, dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHentServicePortType
    {
        
        public IndkomstOplysningPersonHentServicePortTypeClient()
        {
        }
        
        public IndkomstOplysningPersonHentServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public IndkomstOplysningPersonHentServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public IndkomstOplysningPersonHentServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public IndkomstOplysningPersonHentServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentResponse dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHentServicePortType.getIndkomstOplysningPersonHent(dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentRequest request)
        {
            return base.Channel.getIndkomstOplysningPersonHent(request);
        }
        
        public dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHent_OType getIndkomstOplysningPersonHent(dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHent_IType IndkomstOplysningPersonHent_I)
        {
            dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentRequest inValue = new dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentRequest();
            inValue.IndkomstOplysningPersonHent_I = IndkomstOplysningPersonHent_I;
            dk.skat.eksternwiki.demotin.getIndkomstOplysningPersonHentResponse retVal = ((dk.skat.eksternwiki.demotin.IndkomstOplysningPersonHentServicePortType)(this)).getIndkomstOplysningPersonHent(inValue);
            return retVal.IndkomstOplysningPersonHent_O;
        }
    }
}
